name: Python Publish

on:
  workflow_call:
    inputs:

      build_tooling_command:
        type: string
        default: "pip install build"

      build_command:
        type: string
        default: "python -m build"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout    
        uses: actions/checkout@v5
      
      - name: Setup Python         
        uses: actions/setup-python@v6
        with:
          python-version: "3.10" # Lowest supported version

      - name: Install Build Tooling
        run: ${{ inputs.build_tooling_command }}

      - name: Build
        run: ${{ inputs.build_command }}

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist
