name: Python Test

on:
  workflow_call:
    inputs:

      python_versions:
        type: string
        default: '["3.10"]'
      
      os:
        type: string
        default: '["ubuntu-latest"]'
      
      package_manager_command:
        type: string   
        default: '' 
      
      install_command:
        type: string
        default: "pip install -r requirements.txt"
      
      test_command:
        type: string
        default: "python -m pytest"        


jobs:

  detect:
    runs-on: ubuntu-latest
    outputs:
      allow_test: ${{ steps.set.outputs.allow_test }}

    steps:
      - uses: actions/checkout@v5

      - name: Detect internal dependencies
        id: set
        run: |
          # Default to true
          echo "allow_test=true" >> $GITHUB_OUTPUT

          # Only run detection if Dependabot triggered this
          if [ "${GITHUB_ACTOR}" != "dependabot[bot]" ]; then
            echo "allow_test=true" >> $GITHUB_OUTPUT
            exit 0
          fi

          # If Dependabot triggered, block if URL contains "renalreg"
          if [ -f requirements.txt ] && grep -qE 'github\.com[:/]+renalreg/' requirements.txt; then
            echo "allow_test=false" >> $GITHUB_OUTPUT
          fi

          if [ -f pyproject.toml ] && grep -qE 'github\.com[:/]+renalreg/' pyproject.toml; then
            echo "allow_test=false" >> $GITHUB_OUTPUT
          fi

  test:
    needs: detect
    if: ${{ needs.detect.outputs.allow_test == 'true' }}
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform: ${{ fromJSON(inputs.os) }}
        python-version: ${{ fromJSON(inputs.python_versions) }}

    steps:

      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.AL_APP_ID }}
          private-key: ${{ secrets.AL_APP_KEY }}
          owner: renalreg

      - name: Authenticate GitHub HTTPS for private deps
        run: |
          git config --global url."https://x-access-token:${{ steps.generate-token.outputs.token }}@github.com/".insteadOf "https://github.com/"


      - name: Checkout   
        uses: actions/checkout@v5
        
      - name: Setup Python ${{ matrix.python-version }} 
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Package Manager
        if: inputs.package_manager_command != ''
        run: ${{ inputs.package_manager_command }}

      - name: Install Dependencies
        run: ${{ inputs.install_command }}

      - name: Run Tests
        run: ${{ inputs.test_command }}